version: "3.7"

services:
  ernergydb:
    container_name: Mongo-Energy-Services
    image: mongo
    ports:
      - '27020:27017'
    volumes:
      - ./data:/data/ernergydb
  mongo-express:
    container_name: mongo-express-Energy-Services
    image: mongo-express
    depends_on:
      - ernergydb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-express-Energy-Services
    ports:
      - '8089:8081'
    volumes:
      - ./data:/data/energydb